language: python
python: 
  - "3.8"
install:
  - pip install -r requirements.txt


addons:
  sonarcloud:
    organization: "lexel225-sonar"
    token:
      secure: "a9d98da9f121073234d3ad6857d54c5600bc187d"

script:
  - pytest
  - sonar-scanner
